
tasks:
  - name: Install dependencies
    init: npm i && npm install -g json-server -y && gp sync-done frontend
    command: exit
  - name: Run React App
    init: gp sync-await frontend
    command: npm start
  - name: Run Mock API
    init: gp sync-await frontend
    command: json-server --watch db.json --port 5001

ports:
  - name: React App
    port: 3000
    visibility: public
    onOpen: ignore
  - name: Mock API
    port: 5001
    visibility: public
    onOpen: ignore