
tasks:
  - name: Install dependencies
    init: npm i
    command: |
      json-server --watch db.json --port 5001
      npm start

ports:
  - name: React App
    port: 3000
    visibility: public
    onOpen: ignore
  - name: Mock API
    port: 5001
    visibility: public
    onOpen: ignore